### ISSUE TITLE
gfortran

### ISSUE THREAD

**Issue by mee067** [MESH-Model/MESH-Dev#3] opened 2023-01-25 17:05 UTC
Compiled the 1860 code using gfortran (the default when just using make) successfully but it gives memory errors (for several setups) when run. These same setups run fine when compiled using intel 2018 (make ifort). Is there a particular version of gfortran that need to be used? I compiled using 5.4, 6.4, 7.3, and 9.1 all give the same run-time error:
Program received signal SIGSEGV: Segmentation fault - invalid memory reference
Ther error occurs right after reading all the configuration files and checking the forcing files before it prints "DONE INTITIALIZATION"

r1813 compiles and runs with gfortran

**Comment by dprincz** [comment] 2024-08-08 22:46
Closing. This is a duplicate of #48.

**Closed by dprincz** 2024-08-08 22:46 UTC
Labels: bug, duplicate
